export const USERLIST_FETCH_REQUEST = "USERLIST_FETCH_REQUEST";
export const USERLIST_DELETE_REQUEST = "USERLIST_DELETE_REQUEST";
export const USERLIST_LOCATION_UPDATE_REQUEST =
  "USERLIST_LOCATION_UPDATE_REQUEST";
